# ===============================
# SERVER CONFIG
# ===============================

# Port where Spring Boot will run
server.port=8080


# ===============================
# H2 DATABASE CONFIGURATION
# ===============================

# JDBC URL for H2 in-memory database
# "mem:testdb" means the database exists only while app is running
spring.datasource.url=jdbc:h2:mem:testdb

# H2 database driver
spring.datasource.driver-class-name=org.h2.Driver

# H2 username and password (default)
spring.datasource.username=sa
spring.datasource.password=


# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================

# Automatically create/update database tables based on @Entity classes
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console (VERY useful for learning)
spring.jpa.show-sql=true

# Format SQL queries for readability
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# H2 CONSOLE CONFIGURATION
# ===============================

# Enable H2 web console
spring.h2.console.enabled=true

# URL path to access H2 console
spring.h2.console.path=/h2-console


# Enable actuator endpoints
management.endpoints.web.exposure.include=mappings
management.endpoint.mappings.enabled=true
